/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //docSidebar: [{type: 'autogenerated', dirName: '.'}],
  // But you can create a sidebar manually
  docSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: [
        'introduction/intro',
      ],
    },
    {
      type: 'category',
      label: 'RUM',
      items: [
        'rum/introduction',
        'rum/useCases',
        'rum/rumClient',
        'rum/rumServer',
        'rum/elasticsearch',
        'rum/kibana',
        'rum/troubleshooting',
        'rum/releases',
      ],
    },
    {
      type: 'category',
      label: 'Listener',
      items: [
        'listener/introduction',
        'listener/agent',
        'listener/dataManagement',
        'listener/releases',
      ],
    },
    {
      type: 'category',
      label: 'Synthetic',
      items: [
        'synthetic/introduction',
      ],
    },
    {
      type: 'category',
      label: 'Glossary',
      items: [
        'glossary/webperf',
        'glossary/keyf',
        'glossary/awesome',
      ],
    }
  ],
};

module.exports = sidebars;
